# Data Preprocessing

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [17]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
#dataset.head()

# Taking cate of missing data 

# One way may be to ignore the missing data 

#second way is to replace the data. 
Whenever using an imputer we should first declare the imputer object.We define what missing_values we use and what strategy 
is required. 
After that we give fit() function. and give the values of X
This imputer gives a new matrix and we try to apply those values of the new matrix to the old matrix.
then do transform() function to the same set of values. 


In [18]:
from sklearn.impute import SimpleImputer

In [22]:
impute=SimpleImputer(missing_values=np.nan,strategy='mean')

In [27]:
impute.fit(X[:,1:3])

SimpleImputer(copy=True, fill_value=None, missing_values=nan, strategy='mean',
       verbose=0)

In [29]:
X[:,1:3]=impute.transform(X[:,1:3])

# Encoding Categorical Data


In this section, the sklearn libraries for preprocessing data have been used. In the compose library, the column transformer 
is used. 
we create a column transformer object with encoders and one hot encoder and the column that needs to be encoded. 
The passthrough option is specifically used include all the other columns including the transformed ones. 
then we fit_transform the array and declare that as a new array. 


In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [34]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [35]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


One another function in the preprocessing is the label encoder. It is used for binary labels. 
Hence we use that doe the fit_transform to get binary values for y


In [41]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [42]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Splitting the dataset into the Training set and Test set

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

Feature Scaling is used to put all your parameters in the same scale. 
There are two techniques 
1.Standardization = X-mean(X)
                    __________
                    Standard_deviation(X)

2.Normalization =X-min(x)
                ___________
                max(x)-min(x)
                
No need to apply standard scaler for dummy variables as they might change the meaning. 


In [51]:
from sklearn.preprocessing import StandardScaler

In [53]:
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])

C:\Users\vvs87\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\vvs87\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [54]:
X_test[:,3:]=sc.fit_transform(X_test[:,3:])

C:\Users\vvs87\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\vvs87\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [56]:
X_test

array([[0.0, 1.0, 0.0, -1.0, -1.0],
       [0.0, 1.0, 0.0, 1.0, 1.0]], dtype=object)